-- Add 'timing-contact' and 'approach-performance' to the diagnostic_type CHECK constraint.
-- These are new optional hitting vault diagnostics.

-- Drop the existing CHECK constraint and re-create with expanded values.
-- The constraint name is auto-generated by Postgres as: diagnostic_submissions_diagnostic_type_check
ALTER TABLE diagnostic_submissions
  DROP CONSTRAINT IF EXISTS diagnostic_submissions_diagnostic_type_check;

ALTER TABLE diagnostic_submissions
  ADD CONSTRAINT diagnostic_submissions_diagnostic_type_check
  CHECK (diagnostic_type IN (
    'archetype','identity','habits',
    'mover-type','mechanical','lifting-mover',
    'timing-contact','approach-performance'
  ));
